import type { Metadata } from "next";
import "@/assets/css/globals.css";
import "normalize.css"; // reset.css
import { poppins } from "@/assets/fonts/fonts";
import { ThemeProvider } from "@/stores/providers/theme-provider";
import { MainNav } from "@/components/(overview)";

export const metadata: Metadata = {
  title: "HJ Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/HJ..svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`${poppins.className} w-full flex h-screen flex-col justify-center`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* 네비 게이션 */}
          <MainNav />

          {/* 콘텐츠 */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
