import type { Metadata } from "next";
import "@/assets/css/globals.css";
import "normalize.css"; // reset.css
import MainNav from "@/components/main-nav";
import { ThemeProvider } from "@/components/theme-provider";
import { poppins } from "@/assets/fonts/fonts";
export const metadata: Metadata = {
  title: "HJ Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`${poppins.className} w-full flex h-screen flex-col justify-center`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* 네비 게이션 */}
          <MainNav />
          {/* 콘텐츠 */}
          <div className="w-full flex h-screen  flex-col overflow-y-auto scrollbar-hide ">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
